import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const SRC = path.resolve(import.meta.dirname, "../src");

// --- SQL Parser ---

interface Column {
  name: string;
  type: string;
  notNull: boolean;
  primaryKey: boolean;
  default: string | null;
}

interface Table {
  name: string;
  columns: Column[];
  compositePrimaryKey: string[] | null;
}

function parseSql(sql: string): Table[] {
  const tables: Table[] = [];
  const tableRegex =
    /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(\w+)\s*\(([\s\S]*?)\);/gi;

  let match;
  while ((match = tableRegex.exec(sql)) !== null) {
    const tableName = match[1]!;
    const body = match[2]!;
    const columns: Column[] = [];
    let compositePrimaryKey: string[] | null = null;

    for (const raw of splitColumns(body)) {
      const line = raw.trim();
      if (!line) continue;

      // Composite PRIMARY KEY constraint
      const pkMatch = line.match(
        /^PRIMARY\s+KEY\s*\(\s*(.+?)\s*\)$/i,
      );
      if (pkMatch) {
        compositePrimaryKey = pkMatch[1]!.split(",").map((s) => s.trim());
        continue;
      }

      // Column definition
      const colMatch = line.match(/^(\w+)\s+(\w+)(.*)$/i);
      if (!colMatch) continue;

      const name = colMatch[1]!;
      const type = colMatch[2]!.toUpperCase();
      const rest = colMatch[3]!.toUpperCase();

      columns.push({
        name,
        type,
        notNull: rest.includes("NOT NULL"),
        primaryKey: rest.includes("PRIMARY KEY"),
        default: extractDefault(rest),
      });
    }

    tables.push({ name: tableName, columns, compositePrimaryKey });
  }

  return tables;
}

function splitColumns(body: string): string[] {
  const parts: string[] = [];
  let depth = 0;
  let current = "";

  for (const char of body) {
    if (char === "(") depth++;
    else if (char === ")") depth--;

    if (char === "," && depth === 0) {
      parts.push(current);
      current = "";
    } else {
      current += char;
    }
  }
  if (current.trim()) parts.push(current);

  return parts;
}

function extractDefault(rest: string): string | null {
  const match = rest.match(/DEFAULT\s+(\S+)/i);
  return match ? match[1]! : null;
}

// --- Helpers ---

function snakeToCamel(s: string): string {
  return s.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function tableToPascal(s: string): string {
  return s
    .split("_")
    .map((w) => w[0]!.toUpperCase() + w.slice(1))
    .join("");
}

// --- Kysely type generator ---

function generateKyselyTypes(
  tables: Table[],
  dialect: "sqlite" | "postgres",
): string {
  const lines: string[] = [
    "// Auto-generated by scripts/generate.ts — do not edit manually",
    "",
  ];

  for (const table of tables) {
    const interfaceName = tableToPascal(table.name);
    lines.push(`export interface ${interfaceName} {`);

    for (const col of table.columns) {
      const baseType = sqlTypeToTs(col.type, dialect);
      const nullable = !col.notNull && !col.primaryKey;
      const tsType = nullable ? `${baseType} | null` : baseType;
      lines.push(`  ${col.name}: ${tsType};`);
    }

    lines.push("}");
    lines.push("");
  }

  const dbName = dialect === "sqlite" ? "DB" : "Database";
  lines.push(`export interface ${dbName} {`);
  for (const table of tables) {
    lines.push(`  ${table.name}: ${tableToPascal(table.name)};`);
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function sqlTypeToTs(
  sqlType: string,
  dialect: "sqlite" | "postgres",
): string {
  switch (sqlType) {
    case "TEXT":
      return "string";
    case "INTEGER":
      return "number";
    case "JSONB":
      return dialect === "postgres" ? "unknown" : "string";
    default:
      return "string";
  }
}

// --- Drizzle schema generator ---

function generateDrizzleSchema(
  tables: Table[],
  dialect: "sqlite" | "postgres",
): string {
  const lines: string[] = [
    "// Auto-generated by scripts/generate.ts — do not edit manually",
  ];

  // Collect needed imports
  const colTypes = new Set<string>();
  let needsPrimaryKey = false;

  for (const table of tables) {
    for (const col of table.columns) {
      if (dialect === "sqlite") {
        colTypes.add(col.type === "TEXT" ? "text" : "integer");
      } else {
        if (col.type === "JSONB") colTypes.add("jsonb");
        else if (col.type === "TEXT") colTypes.add("text");
        else colTypes.add("integer");
      }
    }
    if (table.compositePrimaryKey) needsPrimaryKey = true;
  }

  if (dialect === "sqlite") {
    const imports = ["sqliteTable", ...colTypes];
    if (needsPrimaryKey) imports.push("primaryKey");
    lines.push(
      `import { ${imports.join(", ")} } from "drizzle-orm/sqlite-core";`,
    );
  } else {
    const imports = ["pgTable", ...colTypes];
    if (needsPrimaryKey) imports.push("primaryKey");
    lines.push(
      `import { ${imports.join(", ")} } from "drizzle-orm/pg-core";`,
    );
  }
  lines.push("");

  for (const table of tables) {
    const varName = snakeToCamel(table.name);
    const tableFunc = dialect === "sqlite" ? "sqliteTable" : "pgTable";

    lines.push(
      `export const ${varName} = ${tableFunc}("${table.name}", {`,
    );

    for (const col of table.columns) {
      const propName = snakeToCamel(col.name);
      const colFunc = drizzleColFunc(col.type, dialect);
      // Only pass column name arg if it differs from the property name
      const nameArg = propName !== col.name ? `"${col.name}"` : "";

      let chain = `${colFunc}(${nameArg})`;
      if (col.default !== null) chain += `.default(${col.default})`;
      if (col.notNull || col.primaryKey) chain += ".notNull()";
      if (col.primaryKey) chain += ".primaryKey()";

      lines.push(`  ${propName}: ${chain},`);
    }

    if (table.compositePrimaryKey) {
      lines.push(`}, (table) => [`);
      const colRefs = table.compositePrimaryKey
        .map((c) => `table.${snakeToCamel(c)}`)
        .join(", ");
      lines.push(`  primaryKey({ columns: [${colRefs}] }),`);
      lines.push(`]);`);
    } else {
      lines.push(`});`);
    }

    lines.push("");
  }

  return lines.join("\n");
}

function drizzleColFunc(
  sqlType: string,
  dialect: "sqlite" | "postgres",
): string {
  if (sqlType === "JSONB" && dialect === "postgres") return "jsonb";
  if (sqlType === "TEXT") return "text";
  return "integer";
}

// --- Main ---

function main() {
  const sqliteSql = readFileSync(path.join(SRC, "sql/sqlite.sql"), "utf-8");
  const postgresSql = readFileSync(
    path.join(SRC, "sql/postgres.sql"),
    "utf-8",
  );

  const sqliteTables = parseSql(sqliteSql);
  const postgresTables = parseSql(postgresSql);

  const files = [
    [
      path.join(SRC, "adapter-sqlite/types.ts"),
      generateKyselyTypes(sqliteTables, "sqlite"),
    ],
    [
      path.join(SRC, "adapter-postgres/types.ts"),
      generateKyselyTypes(postgresTables, "postgres"),
    ],
    [
      path.join(SRC, "adapter-drizzle-better-sqlite/schema.ts"),
      generateDrizzleSchema(sqliteTables, "sqlite"),
    ],
    [
      path.join(SRC, "adapter-drizzle-node-postgres/schema.ts"),
      generateDrizzleSchema(postgresTables, "postgres"),
    ],
  ] as const;

  for (const [filePath, content] of files) {
    writeFileSync(filePath, content);
    console.log(`Generated ${path.relative(process.cwd(), filePath)}`);
  }
}

main();
