packages:
  - packages/*
  - examples/*
  - website

managePackageManagerVersions: false
strictDepBuilds: false

onlyBuiltDependencies:
  - '@prisma/engines'
  - better-sqlite3
  - esbuild
  - prisma
  - sharp
