/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface WorkflowState {
  error: string | null;
  finished_at: number | null;
  input: Json | null;
  lease_expired_at: number;
  resume_at: number;
  run_id: string;
  started_at: number;
  workflow_id: string;
}

export interface WorkflowStepState {
  attempt: Generated<number>;
  error: string | null;
  result: Json | null;
  run_id: string;
  step_id: string;
}

export interface DB {
  workflow_state: WorkflowState;
  workflow_step_state: WorkflowStepState;
}
