// Auto-generated by scripts/generate.ts — do not edit manually

import type { ColumnType } from "kysely";

type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

export interface WorkflowState {
  workflow_id: string;
  run_id: string;
  error: string | null;
  input: JsonValue | null;
  lease_expired_at: number;
  started_at: number;
  finished_at: number | null;
  resume_at: number;
}

export interface WorkflowStepState {
  run_id: string;
  step_id: string;
  result: JsonValue | null;
  error: string | null;
  attempt: ColumnType<number, number | undefined, number>;
}

export interface Database {
  workflow_state: WorkflowState;
  workflow_step_state: WorkflowStepState;
}
