// Auto-generated by scripts/generate.ts — do not edit manually

export interface WorkflowState {
  workflow_id: string;
  run_id: string;
  error: string | null;
  input: string | null;
  leaseExpiredAt: number;
  started_at: number;
  finished_at: number | null;
  resume_at: number;
}

export interface WorkflowStepState {
  run_id: string;
  step_id: string;
  result: string | null;
  error: string | null;
  attempt: number;
}

export interface DB {
  workflow_state: WorkflowState;
  workflow_step_state: WorkflowStepState;
}
