// Auto-generated by scripts/generate.ts — do not edit manually

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface WorkflowState {
  workflow_id: string;
  run_id: string;
  error: string | null;
  input: string | null;
  leaseExpiredAt: number;
  started_at: number;
  finished_at: number | null;
  resume_at: number;
}

export interface WorkflowStepState {
  run_id: string;
  step_id: string;
  result: string | null;
  error: string | null;
  attempt: Generated<number>;
}

export interface DB {
  workflow_state: WorkflowState;
  workflow_step_state: WorkflowStepState;
}
